services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    environment:
      HOME: /tmp
    volumes:
      - ./app:/app
    command: make dev
    ports:
      - "8080:8080"
